### ISSUE TITLE
DoMultipartFormRequest CC Email

### ISSUE THREAD

**Issue by sloppypointless** [jjb3rd/Freshdesk.Net#12]
When using the DoMultipartFormRequest functionality if you provide any values in the cc_emails it causes a 500 error.

**Comment by sloppypointless** [comment]
Sending a push request for the fix.

**Comment by jjb3rd** [comment]
Thanks!  Sorry it's taken a while for me to get to this.

**Comment by sloppypointless** [comment]
No problem!  Glad to see the contribution helped.
