### ISSUE TITLE
Customer and Contact Unit tests failing..

### ISSUE THREAD

**Issue by Zapbbx** [jjb3rd/Freshdesk.Net#3]
I haven't made any changes, when I run the unit tests I get:

Test Name:	TestFreshdeskCreateContact
Test FullName:	Freshdesk.Tests.UserTests.TestFreshdeskCreateContact
Test Source:	\UserTests.cs : line 31
Test Outcome:	Failed
Test Duration:	0:00:00.2312661

Result Message:	
Test method Freshdesk.Tests.UserTests.TestFreshdeskCreateContact threw exception: 
System.Net.WebException: The remote server returned an error: (422) Unprocessable Entity.
Result StackTrace:	
at System.Net.HttpWebRequest.GetResponse()
   at Freshdesk.FreshdeskService.DoRequest(Uri uri, String method, String body)

Test Name:	TestFreshdeskCreateCustomer
Test FullName:	Freshdesk.Tests.CustomerTests.TestFreshdeskCreateCustomer
Test Source:	CustomerTests.cs : line 31
Test Outcome:	Failed
Test Duration:	0:00:00.519684

Result Message:	
Test method Freshdesk.Tests.CustomerTests.TestFreshdeskCreateCustomer threw exception: 
System.Net.WebException: The remote server returned an error: (422) Unprocessable Entity.
Result StackTrace:	
at System.Net.HttpWebRequest.GetResponse()
   at Freshdesk.FreshdeskService.DoRequest(Uri uri, String method, String body)

**Comment by solidcloudio** [comment]
This could be caused by:
[["primary_email.email","has already been taken"],["base","Email has already been taken"]]
or
[["name","has already been taken"]]

**Comment by jjb3rd** [comment]
@solidcloudio is correct...this is generally caused by the name or email having already been taken.  In a future update I may make the test generate a random email.
